import type { CSSProperties } from "react";

// Palet warna halaman RSVP (amplop + form) per tema undangan.
// key = nilai `theme` di URL / database (lihat lib/themes.ts).
// Tema yang belum ada di sini otomatis memakai palet "default".
// Menambah tema baru: cukup tambah satu entri di PALETTES.

type Palette = {
  dark?: boolean;
  bgTop: string;
  bgBottom: string;
  text: string;
  muted: string;
  label: string; // teks kecil/label, harus terbaca di atas bg
  accent: string;
  accentLight: string;
  accentDark: string;
  onAccent: string; // teks di atas tombol
  card: string;
  border: string;
  field: string;
  fieldDisabled: string;
  placeholder: string;
  glow2: string; // pendar kedua di pojok
  paper: string; // badan amplop
  paperIn: string; // bagian dalam amplop
  flap: string; // tutup amplop (tertutup)
  flapIn: string; // tutup amplop (terbuka)
  seal: string;
  sealText: string;
  envInk: string; // tulisan di depan amplop
  letter: string; // kertas yang keluar dari amplop
};

const DEFAULT: Palette = {
  bgTop: "#fffdf8",
  bgBottom: "#f3ecdf",
  text: "#3b3126",
  muted: "#7d705e",
  label: "#8a6a2f",
  accent: "#c29a3e",
  accentLight: "#dcb85f",
  accentDark: "#8a6420",
  onAccent: "#3a2a0c",
  card: "rgb(255 255 255 / 0.8)",
  border: "#e7dcc6",
  field: "#fffdf9",
  fieldDisabled: "#f1ece2",
  placeholder: "#b9ad9a",
  glow2: "#cddcc4",
  paper: "#f2e6cf",
  paperIn: "#e3d3b4",
  flap: "#ead9b8",
  flapIn: "#d9c6a1",
  seal: "#b8893a",
  sealText: "#fff8e6",
  envInk: "#7a5f2c",
  letter: "#fffdf8",
};

const PALETTES: Record<string, Palette> = {
  rustic: {
    ...DEFAULT,
    bgTop: "#f6eee3",
    bgBottom: "#e9dcc8",
    text: "#3d2c1e",
    muted: "#7a6652",
    label: "#8a5a30",
    accent: "#a8693a",
    accentLight: "#c98a58",
    accentDark: "#7a4524",
    onAccent: "#fff6ea",
    card: "rgb(255 250 242 / 0.85)",
    border: "#dcc7a8",
    field: "#fffaf2",
    fieldDisabled: "#efe3d0",
    placeholder: "#b09a80",
    glow2: "#d9c3a0",
    paper: "#d8b98c",
    paperIn: "#b99870",
    flap: "#cfae7e",
    flapIn: "#b8956a",
    seal: "#8c4a2a",
    sealText: "#fbe9d3",
    envInk: "#5b3d22",
    letter: "#fffaf0",
  },
  cinematic: {
    dark: true,
    bgTop: "#14161a",
    bgBottom: "#0b0c0e",
    text: "#f1ece0",
    muted: "#9aa0a8",
    label: "#dfba6b",
    accent: "#dfba6b",
    accentLight: "#f3d58e",
    accentDark: "#b89742",
    onAccent: "#1b1405",
    card: "rgb(24 26 30 / 0.8)",
    border: "rgb(223 186 107 / 0.25)",
    field: "#101215",
    fieldDisabled: "#1b1d21",
    placeholder: "#6b7078",
    glow2: "#7a5c1a",
    paper: "#23262b",
    paperIn: "#15171a",
    flap: "#2c3036",
    flapIn: "#1c1f23",
    seal: "#dfba6b",
    sealText: "#1b1405",
    envInk: "#dfba6b",
    letter: "#1b1d21",
  },
  adatSunda: {
    ...DEFAULT,
    bgTop: "#fbf6e8",
    bgBottom: "#ece3c6",
    text: "#2a3a2e",
    muted: "#6a7766",
    label: "#1f5a3e",
    onAccent: "#17301f",
    card: "rgb(255 252 243 / 0.85)",
    border: "#d9cfa6",
    field: "#fffdf6",
    fieldDisabled: "#eee8d0",
    placeholder: "#a9ad98",
    glow2: "#b9d3bf",
    paper: "#2f6b4d",
    paperIn: "#1f4a35",
    flap: "#286046",
    flapIn: "#1b432f",
    seal: "#c29a3e",
    sealText: "#1c2e22",
    envInk: "#e8d9a4",
    letter: "#fffaf0",
  },
  floral_luxury: {
    ...DEFAULT,
    bgTop: "#fff6f6",
    bgBottom: "#f7dfe0",
    text: "#4a2f35",
    muted: "#8b6a70",
    label: "#a4505f",
    accent: "#c06c7b",
    accentLight: "#dc8f9c",
    accentDark: "#8f4452",
    onAccent: "#fff5f6",
    card: "rgb(255 252 252 / 0.85)",
    border: "#efcdd1",
    field: "#fffafa",
    fieldDisabled: "#f6e6e8",
    placeholder: "#c4a3a8",
    glow2: "#f6c1c8",
    paper: "#f5cfd3",
    paperIn: "#e8b4ba",
    flap: "#f0c0c6",
    flapIn: "#e3a6ae",
    seal: "#b04f60",
    sealText: "#fff0f2",
    envInk: "#8f4452",
    letter: "#fffafa",
  },
  modern: {
    ...DEFAULT,
    bgTop: "#fafafa",
    bgBottom: "#ececec",
    text: "#1f2430",
    muted: "#6b7280",
    label: "#374151",
    accent: "#1f2937",
    accentLight: "#4b5563",
    accentDark: "#111827",
    onAccent: "#ffffff",
    card: "rgb(255 255 255 / 0.9)",
    border: "#e0e2e6",
    field: "#ffffff",
    fieldDisabled: "#f1f2f4",
    placeholder: "#a0a4ac",
    glow2: "#d4d8e0",
    paper: "#e5e7eb",
    paperIn: "#d1d5db",
    flap: "#dcdfe4",
    flapIn: "#c4c8cf",
    seal: "#1f2937",
    sealText: "#ffffff",
    envInk: "#374151",
    letter: "#ffffff",
  },
  sage: {
    ...DEFAULT,
    bgTop: "#f6f8f1",
    bgBottom: "#dfe8d5",
    text: "#2c3a2b",
    muted: "#6a7a66",
    label: "#4f6e45",
    accent: "#6f8f62",
    accentLight: "#93b085",
    accentDark: "#4a6740",
    onAccent: "#f6fbf2",
    card: "rgb(252 254 249 / 0.85)",
    border: "#d3e0c8",
    field: "#fcfef9",
    fieldDisabled: "#ebf1e4",
    placeholder: "#a3b09c",
    glow2: "#b9d3a8",
    paper: "#c5d6b9",
    paperIn: "#a9c09b",
    flap: "#bacdac",
    flapIn: "#9db78e",
    seal: "#56743f",
    sealText: "#f4faee",
    envInk: "#3f5a36",
    letter: "#fbfdf8",
  },
  midnight: {
    dark: true,
    bgTop: "#1a2150",
    bgBottom: "#0c1030",
    text: "#eef0ff",
    muted: "#9aa3cf",
    label: "#e8bfd0",
    accent: "#e2b8c8",
    accentLight: "#f3d2de",
    accentDark: "#b98aa0",
    onAccent: "#1a1333",
    card: "rgb(26 33 80 / 0.75)",
    border: "rgb(226 184 200 / 0.28)",
    field: "#121842",
    fieldDisabled: "#1b2250",
    placeholder: "#6e78ad",
    glow2: "#5b4aa6",
    paper: "#2a3370",
    paperIn: "#1a2150",
    flap: "#333d82",
    flapIn: "#232b66",
    seal: "#e2b8c8",
    sealText: "#1a1333",
    envInk: "#e8bfd0",
    letter: "#1e2559",
  },
  japandi: {
    ...DEFAULT,
    bgTop: "#f6f3ed",
    bgBottom: "#e5dfd2",
    text: "#35302a",
    muted: "#7a7366",
    label: "#7a6a50",
    accent: "#8a7a62",
    accentLight: "#a8997f",
    accentDark: "#5f523f",
    onAccent: "#fbf8f1",
    card: "rgb(252 250 245 / 0.88)",
    border: "#dcd5c6",
    field: "#fdfbf7",
    fieldDisabled: "#ece7db",
    placeholder: "#aaa292",
    glow2: "#cfc7b2",
    paper: "#d8d0bf",
    paperIn: "#c1b8a4",
    flap: "#cec5b2",
    flapIn: "#b8ae98",
    seal: "#6b5d47",
    sealText: "#f8f4ea",
    envInk: "#5f523f",
    letter: "#fcfaf5",
  },
};

// Mengubah palet tema jadi CSS variable untuk dipasang di elemen root halaman RSVP.
export function rsvpThemeStyle(theme: string): CSSProperties {
  const p = PALETTES[theme] ?? DEFAULT;
  const vars: Record<string, string> = {
    "--rv-bg-top": p.bgTop,
    "--rv-bg-bottom": p.bgBottom,
    "--rv-text": p.text,
    "--rv-muted": p.muted,
    "--rv-label": p.label,
    "--rv-gold": p.accent,
    "--rv-gold-light": p.accentLight,
    "--rv-gold-dark": p.accentDark,
    "--rv-on-accent": p.onAccent,
    "--rv-card": p.card,
    "--rv-border": p.border,
    "--rv-field": p.field,
    "--rv-field-disabled": p.fieldDisabled,
    "--rv-placeholder": p.placeholder,
    "--rv-error": p.dark ? "#ff8a80" : "#b4352a",
    "--rv-sage": p.glow2,
    "--ev-paper": p.paper,
    "--ev-paper-in": p.paperIn,
    "--ev-flap": p.flap,
    "--ev-flap-in": p.flapIn,
    "--ev-seal": p.seal,
    "--ev-seal-text": p.sealText,
    "--ev-ink": p.envInk,
    "--ev-letter": p.letter,
  };
  return { ...vars, colorScheme: p.dark ? "dark" : "light" } as CSSProperties;
}
